POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJqb2huREBnbWFpbC5jb20iLCJpYXQiOjE3MDQyMDU2MjN9.I1uKKXpWaR70rMkTNXaGq4Mr6vuj5x6t1SHVDJoF9pc

{
    "author": "Jimmy Doolittle",
    "url": "http://fakeblogaddress.com",
    "title": "A new blog post",
    "likes": 10,
    "year": 2022
}