POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJqb2huREBnbWFpbC5jb20iLCJpYXQiOjE3MDQxMDEzMTR9.-H11xYCHhdr1HGJcOHcqvpfyrl7raNLEnoQw9ezKm08

{
    "author": "Jimmy Doolittle",
    "url": "http://fakeblogaddress.com",
    "title": "A new blog post",
    "likes": 10
}